### ISSUE TITLE
Impossible to remove permissions section from repo settings

### ISSUE THREAD

**Issue by olenagerasimova** [artipie/management-api#42]
Permissions section is not removed when repo settings are updated from
```
repo:
  type: file
  storage: default
  permissions:
    artipie:
      - download
```
to 
```
repo:
  type: file
  storage: default
```
Permissions section is not required, so second yaml is valid and correct. Also, not required section `settings` is added on update with value `null`.
