### ISSUE TITLE
`ApiRepoUpdateSlice` swallows some values

### ISSUE THREAD

**Issue by genryxy** [artipie/management-api#54]
When you update config settings through api, it does not work in a proper way. For example there is the following config file
```yaml
repo:
  type: php
  storage: default
  permissions:
    "*":
      - download
```
And it is necessary to change this file in this way:
```yaml
repo:
  type: php
  storage: default
  url: "http://localhost:8080"
  permissions:
    "*":
      - download
```
It saves only basic content of config file. Looks like some field from source yaml config are not read during copying
